# Header
menu:
  Inicio: /
  Archivo: /archives
  Nosotros: /nosotros
  Github: https://github.com/nodebots-sv/
rss: /atom.xml

# Content
excerpt_link: Seguir leyendo
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-64905810-1
favicon: /favicon.png
twitter: NodebotsSV
google_plus: 109141445080131736818
fb_admins:
fb_app_id:
